### ISSUE TITLE
Searching for program: No such file or directory, sqlite3

### ISSUE THREAD

**Issue by Bullish-Design** [ahyatt/ekg#104]
I had ekg up and running on a previous init.el file, and then decided to "start fresh". Clean ubuntu install (on wsl2) clean build of emacs 29.1. Trying to open ekg gives a "Searching for program: No such file or directory, sqlite3" error. Everything was installed via straight.el from the get go. My init file is attached below. 

I'm able to open the triples.db file via "sqlite-mode-open-file", which is extra odd. 

I'm not even sure where this is stemming from in the EKG package. Any thoughts? 

[test.md](https://github.com/ahyatt/ekg/files/12744864/test.md)

**Comment by Bullish-Design** [comment]
Simple mistake on my part. I somehow skipped over the "apt install sqlite3" during my ubuntu setup script. 

Though it does bring up the question - how did the triples database manage to initialize itself, and emacs sqlite-mode-open-file manage to interact with it?

**Comment by ahyatt** [comment]
I don't think you should need sqlite3 installed with emacs 29.1, unless you are using an emacs 29.1 that left out sqlite when compiling.  So that sounds wrong.  I suspect you might be using ekg via emacsql instead of using the built-in sqlite.   I'm not sure how that would have happened, though.  You can find out by checking the value of `triples-sqlite-interface`.  It should be `builtin`, but I suspect yours will be `emacsql`.

You can also try `(sqlite-available-p)`, which should be non-nil for most emacs 29.1.  If yours is `nil`, that would confirm that your emacs was compiled without sqlite.
