### ISSUE TITLE
ekg-upgrade-db: Searching for program: No such file or directory, sqlite3

### ISSUE THREAD

**Issue by sg-qwt** [ahyatt/ekg#127]
Hi,

I installed fresh ekg from melpa. 

I tried both melpa stable (0.4.2) and melpa (20231111.513).

On startup calling egk-capture: it reports `ekg-upgrade-db: Searching for program: No such file or directory, sqlite3`

Then if I tried to save any of the new capture buffer, it says: 

```
apply: Database error: "disk I/O error"
Database error: "disk I/O error"
```

Note I'm using emacs29.1 with sqlite builtin:
value of triples-sqlite-interface is builtin, (sqlite-available-p) is t

The same emacs works fine with org-roam with the builtin sqlite.

I'm not sure how to proceed with the debug any further, any help would appreciate.

Thanks!

**Comment by ahyatt** [comment]
Thank you for the bug report!  I think what is happening is that when the upgrade routine is called, it performs a backup.  There is no built-in sqlite backup in emacs.  I've [attempted to add one](https://lists.gnu.org/archive/html/bug-gnu-emacs/2022-11/msg01418.html), but the maintainers disagreed that it was needed.  Because we can't back up via emacs, we have to call out to the sqlite3 executable directly, which you either do not have or is not in your path.  If it's the latter, you can set `triples-sqlite-executable` (which I probably should make into a customized variable).

**Comment by ahyatt** [comment]
I can make backup optional, but I'm not sure if that's a good idea.  I'm a bit afraid of people losing their work if they start using it without backups.

**Comment by ahyatt** [comment]
Good to hear, thanks!  I won't close this out yet, since at the very least we can make a more useful error message.

I may also see if it makes sense to revive that thread and get this into emacs.

**Comment by ahyatt** [comment]
The latest commit should provide a much better experience here.  Thank you for reporting the problem.
