### ISSUE TITLE
Where is ekg database?

### ISSUE THREAD

**Issue by yibie** [ahyatt/ekg#183]
When I swtich .emacs.d folder, notes in ekg are missing.

Where is ekg database? Can I custom the database place?

**Comment by ahyatt** [comment]
The ekg database is stored in the `~/.emacs.d/` folder, which is why if you change your folder, it will not be there.  You can change this by customizing the `ekg-db-file` variable.  You can see [more information in our documentation](https://github.com/ahyatt/ekg/blob/develop/doc/ekg.org#4-database), which should be installed as an info file so should appear in the list of documentation at `M-x info`, or you can look at it online.
