### ISSUE TITLE
ekg-capture-url fails due to uninitialized ekg-db

### ISSUE THREAD

**Issue by jayrajput** [ahyatt/ekg#67]
If I invoke ekg-capture-url after restarting emacs I can see it failing due to uninitialized `ekg-db` variable. Shall the `ekg-capture-url` be calling `ekg-connect` before calling `triples-get-subject`?

**Comment by jayrajput** [comment]
Also does it make sense to call ekg-connect once during the module loading. Is there anything in the emacs package which can be used to initialize the connection one time rather than calling ekg-connect at multiple places?

**Comment by qingshuizheng** [comment]
> If I invoke ekg-capture-url after restarting emacs I can see it failing due to uninitialized `ekg-db` variable

Ah, same issue here. :d

**Comment by ahyatt** [comment]
Let me think about this, yes something should be done, but there's also an issue where we don't want the connection always open because if you upgrade ekg or start using a new ekg module, you want it to add the schema, which is what happens when we reconnect.  I suspect the same solution should fix both problems, ideally.

**Comment by ahyatt** [comment]
I think the commit referenced above should fix the issue, let me know if it does not by re-opening this bug.  Thank you for reporting it!
